name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install conan
      run: pip install conan && conan profile detect --force
    - name: conan install & build
      run: mkdir build && cd build && conan install .. && conan build ..
